/**
 * 🧪 TESTE RÁPIDO DO PARSER DE GCODE
 *
 * Execute este arquivo para testar o parser com exemplos reais.
 *
 * Como rodar:
 * npx ts-node lib/utils/testParseGcode.ts
 */

import { parseGCode, testGCodeParser } from "./parseGcode";

console.log("═══════════════════════════════════════════════════════");
console.log("🧪 TESTE DO PARSER DE GCODE - VULTRIX3D");
console.log("═══════════════════════════════════════════════════════\n");

// ════════════════════════════════════════════════════════════════
// TESTE 1: BAMBU STUDIO MULTI-COLOR
// ════════════════════════════════════════════════════════════════
console.log("🎨 TESTE 1: Bambu Studio Multi-Color (3 filamentos)\n");

const bambuMultiColor = `
; generated by BambuStudio 01.09.05.52 on 2024-01-15 at 14:32:15 UTC
; 
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
;
; layer_height = 0.2
; fill_density = 15%
; wall_loops = 2
; support_enable = 1
; brim_width = 0
; nozzle_temperature = 220
; bed_temperature = 60
; filament_type = PLA;PLA;PETG
; filament_settings_id = Generic PLA @BBL X1C;Bambu PLA Basic @BBL X1C;Generic PETG @BBL X1C
; print_settings_id = 0.20mm Standard @BBL X1C
;
; estimated printing time (normal mode) = 2h 34m 15s
; filament used [g] = 12.34, 23.45, 34.56
; filament used [mm] = 4123.45, 8234.56, 11456.78
;
; total estimated filament weight = 70.35g
; total estimated filament length = 23814.79mm
;
M73 P0 R154
G28 X Y
...
`;

const result1 = parseGCode(bambuMultiColor);
console.log("📊 Resultado:\n");
console.log(`✅ Sucesso: ${result1.success}`);
console.log(
  `⏱️  Tempo: ${result1.estimated_time_minutes} min (${(result1.estimated_time_minutes! / 60).toFixed(2)}h)`,
);
console.log(`⚖️  Peso Total: ${result1.total_weight_grams}g`);
console.log(`🎨 Materiais detectados: ${result1.materials.length}`);
result1.materials.forEach((mat, i) => {
  console.log(`   ${i + 1}. ${mat.name} (${mat.type}) - ${mat.weight_grams}g`);
});
console.log(`🔧 Print Settings:`);
console.log(`   - Layer Height: ${result1.print_settings.layer_height}mm`);
console.log(`   - Infill: ${result1.print_settings.infill_percent}%`);
console.log(`   - Walls: ${result1.print_settings.wall_count}`);
console.log(`   - Nozzle Temp: ${result1.print_settings.nozzle_temp}°C`);
console.log(`   - Bed Temp: ${result1.print_settings.bed_temp}°C`);
console.log(
  `🔨 Slicer: ${result1.slicer_name} ${result1.slicer_version || ""}`,
);
console.log(
  `❌ Erros: ${result1.errors.length > 0 ? result1.errors.join(", ") : "Nenhum"}`,
);
console.log("\n");

// ════════════════════════════════════════════════════════════════
// TESTE 2: ORCA SLICER DUAL COLOR
// ════════════════════════════════════════════════════════════════
console.log("🦑 TESTE 2: Orca Slicer Dual Color (2 filamentos)\n");

const orcaDualColor = `
; generated by OrcaSlicer 1.8.1 on 2024-02-20 at 10:15:30 UTC
; layer_height = 0.15
; fill_density = 20
; wall_loops = 3
; support_enable = 0
; nozzle_temperature = 215
; bed_temperature = 65
; filament_type = PLA;PETG
; filament_settings_id = Polymaker PLA Pro;Generic PETG
; estimated printing time (normal mode) = 1h 23m 45s
; filament used [g] = 25.5, 18.3
; filament used [mm] = 8500.5, 6100.2
G28
...
`;

const result2 = parseGCode(orcaDualColor);
console.log("📊 Resultado:\n");
console.log(`✅ Sucesso: ${result2.success}`);
console.log(`⏱️  Tempo: ${result2.estimated_time_minutes} min`);
console.log(`⚖️  Peso Total: ${result2.total_weight_grams}g`);
console.log(`🎨 Materiais: ${result2.materials.length}`);
result2.materials.forEach((mat, i) => {
  console.log(
    `   ${i + 1}. ${mat.name} (${mat.type}) - ${mat.weight_grams}g - ${mat.length_m?.toFixed(2)}m`,
  );
});
console.log(`🔨 Slicer: ${result2.slicer_name}`);
console.log("\n");

// ════════════════════════════════════════════════════════════════
// TESTE 3: PRUSASLICER SINGLE COLOR
// ════════════════════════════════════════════════════════════════
console.log("🟣 TESTE 3: PrusaSlicer Single Color\n");

const prusaSingle = `
; generated by PrusaSlicer 2.6.1+win64 on 2024-01-15 at 10:20:30 UTC
; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; layer_height = 0.15
; fill_density = 20%
; perimeters = 3
; support_material = 0
; estimated printing time = 1h 23m 45s
; total filament used [g] = 45.67
; total filament used [mm] = 15234.56
M104 S215 ; set temperature
...
`;

const result3 = parseGCode(prusaSingle);
console.log("📊 Resultado:\n");
console.log(`✅ Sucesso: ${result3.success}`);
console.log(`⏱️  Tempo: ${result3.estimated_time_minutes} min`);
console.log(`⚖️  Peso Total: ${result3.total_weight_grams}g`);
console.log(`🎨 Materiais: ${result3.materials.length}`);
if (result3.materials.length > 0) {
  console.log(
    `   1. ${result3.materials[0].name} - ${result3.materials[0].weight_grams}g`,
  );
}
console.log(`🔨 Slicer: ${result3.slicer_name}`);
console.log("\n");

// ════════════════════════════════════════════════════════════════
// TESTE 4: CURA (FORMATO TIME EM SEGUNDOS)
// ════════════════════════════════════════════════════════════════
console.log("🟡 TESTE 4: Cura (formato TIME em segundos)\n");

const curaFormat = `
;Generated with Cura_SteamEngine 5.6.0
;Layer height: 0.2
;Fill density: 15
;TIME:7425
;Filament used: 2.5m, 7.5g
M190 S60
M104 S200
...
`;

const result4 = parseGCode(curaFormat);
console.log("📊 Resultado:\n");
console.log(`✅ Sucesso: ${result4.success}`);
console.log(
  `⏱️  Tempo: ${result4.estimated_time_minutes} min (convertido de ${7425} segundos)`,
);
console.log(`⚖️  Peso Total: ${result4.total_weight_grams}g`);
console.log(`🔨 Slicer: ${result4.slicer_name || "Detectado como Cura"}`);
console.log("\n");

// ════════════════════════════════════════════════════════════════
// TESTE 5: ARQUIVO SEM METADADOS (FALHA ESPERADA)
// ════════════════════════════════════════════════════════════════
console.log("❌ TESTE 5: Arquivo sem metadados (deve falhar)\n");

const emptyGcode = `
G28
G1 X0 Y0 Z0
M104 S200
M109 S200
G1 E10 F200
`;

const result5 = parseGCode(emptyGcode);
console.log("📊 Resultado:\n");
console.log(`✅ Sucesso: ${result5.success} (esperado: false)`);
console.log(`❌ Erros: ${result5.errors.join(", ")}`);
console.log("\n");

console.log("═══════════════════════════════════════════════════════");
console.log("✅ TODOS OS TESTES CONCLUÍDOS!");
console.log("═══════════════════════════════════════════════════════\n");

console.log("💡 Dicas:");
console.log(
  "- Para melhor precisão em multi-cor, use Bambu Studio ou Orca Slicer",
);
console.log("- .gcode sempre é mais confiável que .3mf");
console.log('- Se não detectar breakdown, o sistema criará "Material Único"');
console.log("- Print settings só são extraídos de .gcode, nunca de .3mf");
